### ISSUE TITLE
CSS output file from .vue files is place in 'includes/js'

### ISSUE THREAD

**Issue by iurquiza** [Ortus-Solutions/coldbox-elixir#2]
CSS output file when mixing .vue files is place in 'includes/js' instead of 'includes/css'

**Comment by elpete** [comment]
Are you talking about the `<style>` tag in single-file components?

**Comment by iurquiza** [comment]
Yes, that is the css I am referring to. Elixir mix.vue method creates a css file that matches the vue file's nam and puts it in the includes/js directory. I don't if that is the expected behavior, but if it is please disregard my comment and close the issue.

**Comment by elpete** [comment]
@iurquiza Can you try out `coldbox-elixir@3.0.0-beta.13`?  I've done a lot of work on this and would love your help testing it.

**Comment by elpete** [comment]
Sorry, try `coldbox-elixir@3.0.0-beta.14` instead.

**Comment by iurquiza** [comment]
Sure, I'd be glad to help test it.

**Comment by iurquiza** [comment]
@elpete I get the following error: `Cannot find module 'babel-runtime/core-js/object/assign'`. Once I installed `babel-runtime` I did not get any errors. I think that that node_modules should be listed as a dependency in the `package.json` of the `coldbox-elixir`. There is also a bug that is preventing the js output file from being created. The css file is generated and it is now placed in the `includes/css` directory, but the js directory and file are not created. Let me know if there is anything else I can help with. I will start looking through the code to be of more help. Thanks.

**Comment by iurquiza** [comment]
Had to revert back to `3.0.0-beta.12` to have both files generated.

**Comment by elpete** [comment]
Thanks for the help testing.  Please try `3.0.0-beta.16` at your earliest convenience.

**Comment by iurquiza** [comment]
This time it successfully generates the two files in their respective locations, but the Javascript is not executed. I have double-checked that the files are included in the page. No errors are displayed in the console. It looks very similar to the situation when I had not loaded the `vendor.js` and `runtime.js`. This time I've made sure they are included. When I add the `--display verbose` to the webpack command there does seem to be a line in the output indicating that the runtime is zero bytes `chunk {includes/js/runtime} includes/js/runtime.js (includes/js/runtime) 0 bytes`, but I am just getting familiar with webpack, so I may be completely wrong. See the attached screenshot.

![screen shot 2018-10-31 at 2 04 20 am](https://user-images.githubusercontent.com/6798554/47777596-526d8a00-dcb2-11e8-8eb8-9582e31a9f8a.png)

**Comment by jclausen** [comment]
Going to close this out since v4 is out now and I have not seen this behavior
