### ISSUE TITLE
Elixir Breaks with Webpack 5

### ISSUE THREAD

**Issue by homestar9** [Ortus-Solutions/coldbox-elixir#29]
It looks like webpack doesn't work with the latest webpack.  Running a build will generate the following error:
`ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.`

**Comment by homestar9** [comment]
I should point out that all users will experience this issue if they attempt to resolve npm vulnerabilities using `npm audit fix`.  Fixing vulnerabilities will have the side-effect of upgrading webpack to version 5 and thus break Elixir's ability to run.

**Comment by jclausen** [comment]
This was resolved with the v4 release
