### ISSUE TITLE
entryDirectory behavior is different for .js() than for .css() or .sass()

### ISSUE THREAD

**Issue by DiscountDarcy** [Ortus-Solutions/coldbox-elixir#6]
.js() treats the entryDirectory() value as an absolute path, while .css() and .sass() treat it as a relative path, e.g.

`"entryDirectory" : "/node_modules/foo/resources"` is resolved relative to the webroot for .css() and .sass(), but to `/node_modules` off the filesystem root for .js().

It's easily worked around by using `./` instead of `/` but it seems these should be consistent.

**Comment by jclausen** [comment]
Unfortunately, this is a product of of the loader conventions.  

In the current version of Elixir/Webpack, the prefixing is different:

`scss` - `~` is an alias to the node modules directory
```
@import "~dropzone/dist/dropzone.css";
```

Node modules need no `/node_modules` prefix and are resolved by using just the module name:

```
import "bootstrap-datepicker/dist/js/bootstrap-datepicker.js";
```
